---
- name: Sample Playbook
  hosts: all
  tasks:
    - name: Ping test
      ansible.builtin.ping:

    - name: Run the 'whoami' executable with the '/all' argument
      ansible.windows.win_command:
      cmd: whoami.exe /all
